#!/bin/bash

for f in `ls -d */ | sed 's#/##'`; do
	if name=`grep name $f/Cargo.toml | cut -d\" -f2` ; then
		continue
	fi
	
	if [ "$name" != $f ]; then
 		sed -i "s/${name}/${f}/" $f/Cargo.toml  
	fi
 done                            
